# Generated by Django 2.2.28 on 2022-11-29 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIKeys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=50)),
                ('key', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_name', models.CharField(max_length=250)),
                ('place_type', models.CharField(choices=[('address', 'Address'), ('place', 'City/Town'), ('country', 'Country')], max_length=15)),
                ('latitude', models.CharField(max_length=15)),
                ('longitude', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='WeatherLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_date', models.DateTimeField(verbose_name='date logged')),
                ('main', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('icon', models.CharField(max_length=5)),
                ('temp', models.DecimalField(decimal_places=2, max_digits=4)),
                ('feels_like', models.DecimalField(decimal_places=2, max_digits=4)),
                ('temp_min', models.DecimalField(decimal_places=2, max_digits=4)),
                ('temp_max', models.DecimalField(decimal_places=2, max_digits=4)),
                ('pressure', models.PositiveIntegerField()),
                ('humidity', models.PositiveSmallIntegerField()),
                ('wind_speed', models.FloatField()),
                ('wind_degrees', models.FloatField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather.Location')),
            ],
        ),
    ]
